apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: restart-lobby
spec:
  schedule: '30 8 * * *'
  startingDeadlineSeconds: 120
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        role: restart-lobby
    spec:
      template:
        metadata:
          labels:
            role: restart-lobby
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: Never
          nodeSelector:
            minecraft: 'true'
          containers:
            - name: lobby
              image: stratusnetwork/kubectl:latest
              args:
                - patch
                - statefulset
                - lobby
                - -p
                - "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
              volumeMounts:
                - name: kube
                  mountPath: /config/.kube
          volumes:
            - name: kube
              hostPath:
                path: /root/.kube
