apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapdev
spec:
  serviceName: mapdev
  selector:
    matchLabels:
      role: mapdev
  template:
    metadata:
      labels:
        role: mapdev
    spec:
      nodeSelector:
        minecraft: 'true'
      containers:
        - name: minecraft
          image: gcr.io/stratus-181519/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
            exec:
              command:
                - ./health.sh
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            exec:
              command:
                - ./health.sh
          resources:
            requests:
              cpu: 1000m
              memory: 4Gi
            limits:
              cpu: 1500m
              memory: 4Gi
          envFrom:
            - configMapRef:
                name: mapdev-config
            - configMapRef:
                name: minecraft-config
          volumeMounts:
            - name: dropbox
              mountPath: /minecraft/maps:rw
        - name: dropbox
          image: stratusnetwork/dropbox
          envFrom:
            - secretRef:
                name: dropbox-secret
          env:
            - name: DROPBOX_FOLDER_REMOTE
              value: /mapdev
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 250m
              memory: 300Mi
          volumeMounts:
            - name: dropbox
              mountPath: /dropbox:rw
      volumes:
        - name: dropbox
          hostPath:
            path: /storage/dropbox/mapdev
