apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      role: redis
  template:
    metadata:
      labels:
        role: redis
    spec:
      nodeSelector:
        backend: 'true'
      containers:
        - name: redis
          image: redis:4.0.1-alpine
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 50m
