apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payload
spec:
  serviceName: payload
  replicas: 2
  selector:
    matchLabels:
      role: payload
  template:
    metadata:
      labels:
        role: payload
    spec:
      nodeSelector:
        minecraft: 'true'
      containers:
        - name: payload
          image: gcr.io/stratus-181519/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          resources:
            requests:
              cpu: 1000m
              memory: 4Gi
            limits:
              cpu: 1500m
              memory: 4Gi
          envFrom:
            - configMapRef:
                name: payload-config
            - configMapRef:
                name: minecraft-config
          volumeMounts:
            - name: maps
              mountPath: /minecraft/maps:ro
            - name: rotations
              mountPath: /minecraft/rotations:ro
      volumes:
        - name: maps
          hostPath:
            path: /storage/maps
        - name: rotations
          hostPath:
            path: /storage/rotations
